- hosts: all
  become: yes
  tasks:
  - name: Update apt package
    apt:
      update_cache: yes

  - name: Install the following packages
    ansible.builtin.apt:
      pkg:
        - unzip
        - mariadb-client
        - mariadb-server
      state: present
      update_cache: yes

  - name: Start mariadb by making it permanent
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes
      